title: colemanm.org
name: colemanm.org
description: "Notes + Links from @colemanm"
author:
  name: Coleman McCormick
  email: coleman@mcco.me
  uri: http://www.colemanm.org
permalink: /post/:title/
port: 4001
url: https://www.colemanm.org

collections:
  maps:
    output: true

feed:
  path: atom.xml

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - bundle
  - script
  - CNAME
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-admin
