title: colemanm.org
name: colemanm.org
description: "Notes + Links from @colemanm"
author:
  name: Coleman McCormick
  email: coleman@mcco.me
  uri: https://www.colemanm.org
permalink: /post/:title/
host: 0.0.0.0
port: 4001
url: http://localhost:4001

collections:
  maps:
    output: true
  books:
    output: true
    permalink: /books/:title/
  articles:
    output: true
    permalink: /articles/:title/
  quotes:
    output: true
    permalink: /quotes/:title/
  notes:
    output: true
    permalink: /notes/:title/

sass:
  sass_dir: _sass
  style: :compressed

feed:
  path: atom.xml

exclude:
  - CONTRIBUTING.md
  - README.md
  - bundle
  - script
  - CNAME
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
